{% set name = "l_ozdm" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .
#  git_rev:
#  git_url: https://gitlab.estig.ipb.pt/greenhealth/poselib

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - python
  run:
    - avro >=1.11.2
    - proton >=0.9.1

about:
  home: http://openzdm.eu
  license: PROPRIETARY
  license_family: PROPRIETARY
  summary: Composable command line interface toolkit
